esphome:
  name: th-01

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret th01_encryptionkey

ota:
  password: !secret th01_otapass

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT11
    update_interval: 4s
    temperature:
      name: "Temperature Readout"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
            send_first_at: 15
    humidity:
      name: "Humidity Readout"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
            send_first_at: 15

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Th-01 Fallback Hotspot"
    password: "123456789"

captive_portal:
    
